package com.doctoror.particleswallpaper.framework.app

object HardwareCanvasBlacklist {

    private val blackList = hashSetOf(
        "ailsa_ii",
        "beryllium",
        "bullhead",
        "cactus",
        "chiron",
        "cv7a",
        "degaswifiue",
        "dipper",
        "dream2lte",
        "dream2qltesq",
        "dreamlte",
        "dreamlteks",
        "elsa",
        "F8332",
        "G3123",
        "gemini",
        "grandneove3g",
        "grandpplte",
        "greatlte",
        "hero2lte",
        "heroqlteaio",
        "HWANE",
        "HWCMR09",
        "HWDRA-M",
        "HWDRA-MG",
        "HWMHA",
        "HWPIC",
        "HWSTF",
        "HWWAS-H",
        "jasmine_sprout",
        "joan",
        "land",
        "lithium",
        "mata",
        "nash",
        "nora_8917",
        "OnePlus5T",
        "OnePlus6",
        "P450L10",
        "PLE",
        "polaris",
        "sagit",
        "sakura",
        "sakura_india",
        "scorpio",
        "sirius",
        "taimen",
        "TECNO-CA7",
        "tissot_sprout",
        "tulip",
        "ursa",
        "vince",
        "wayne",
        "whyred",
        "ysl",
        "ZS570KL"
    )

    fun isBlacklistedForLockHardwareCanvas(device: String, product: String) =
        blackList.contains(device) || blackList.contains(product)
}
